name: zsh-benchmark

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Remove .gitconfig
        run: rm ~/.gitconfig

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install gnu-time
        run: brew install gnu-time

      - name: Setup
        run: ./bootstrap.sh

      - name: Run Benchmark
        run: ./github/scripts/zsh-benchmark.sh > result.json

      - name: Dump Benchmark
        run: cat result.json

      - uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: result.json
          benchmark-data-dir-path: zsh/bench
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: "150%"
          alert-comment-cc-users: "@yhino"
